import { POKEMON_GRAPH_QL_ENDPOINT_BASE_URL } from "./endpoints";
import { PAGE_SIZE } from "./pagination";
import { LOCAL_STORAGE_FAV_KEY } from "./storage";
import { LAUNCH_DATA_TTL, RETRY_ATTEMPTS, RETRY_DELAY } from "./ttl";

export {
	// LOCAL STORAGE
	LOCAL_STORAGE_FAV_KEY,

	// ENDPOINTS
	POKEMON_GRAPH_QL_ENDPOINT_BASE_URL,

	// TTLs
	LAUNCH_DATA_TTL,
	RETRY_ATTEMPTS,
	RETRY_DELAY,

	// PAGINATION
	PAGE_SIZE,
};
